【Fixed】株式会社万葉様新入社員研修課題Step5が完了しました。
hrnrssk/manyou_step1 pull request #7
Opened 2020-10-08 18:24 UTC by hrnrssk

#6 

- [ ] Railsが用意しているデフォルトのエラーページを、自分が作った画面にする
- [ ] 状況に応じて、適切にエラーページを設定する
- [ ] ステータスコードの404ページと500ページの2種類の設定は必須とする
- [ ] それ以外は+α要件として、つけてみたい方は実装してみること
- [ ] タスクに複数のラベルをつけられる（ラベルはseedなどのマスタデータで作成する・管理する形でも構いませんし、管理画面などから作成できる形でも構わない）
- [ ] ラベルは、タスクを新規登録するときに（またはタスクの編集をするときに）タスクと一緒に登録（または編集）できる
- [ ] タスクの詳細画面で、そのタスクに紐づいているラベル一覧を出力する
- [ ] 【+α要件】ユーザが自分でラベルを作成ができる（その場合、ユーザが作成したラベルはそのユーザしか使えないように実装すること）
- [ ] 【+α要件】タスクを編集するとき、タスクに紐づいているラベルも一緒に編集（ラベルの付け外し）ができる
- [ ] つけたラベルで検索ができる（ラベルは一つだけを選択して、そのラベルがついているタスクを検索するという形で構いません）
- [ ] 今回は、実装した内容を参考に必要なテスト項目を自分で考えSystem Specを書く
- [ ] テストが通ったときのスクショをコメントと一緒に貼り付ける
- [ ] ラベルはGemを使わず実装する
- [ ] step5のブランチからHerokuのmasterにpushする
- [ ] それぞれ10件以上のタスク、ユーザ、ラベルのシードデータをHerokuに反映させる
- [ ] HerokuのURLを提出する

2020-10-10 04:29 UTC, yuji91 requested changes
コーディングレベルで気になった点を指摘しました。

修正の際は指摘内容ごとにコミットの単位を分けて、「Fix: ~~を修正」などプレフィックスをつけてコミットメッセージを作成頂くと良いと思います。

2020-10-10 04:29 UTC, yuji91 commented on app/controllers/tasks_controller.rb
> +  # end
こちら残しておく必要のないコメントアウトは削除をお願いします。

2020-10-10 04:29 UTC, yuji91 commented on app/views/tasks/_form.html.erb
> +=end%>
こちらも必要のないコメントは削除をお願いします。

2020-10-10 04:29 UTC, yuji91 commented on app/views/tasks/index.html.erb
> +=end%>
こちらも削除をお願いします。

2020-10-10 04:29 UTC, yuji91 commented on db/migrate/20201004174903_create_labels.rb
> +      t.string :name
null制約は付与しなくて大丈夫でしょうか？

2020-10-10 04:29 UTC, yuji91 commented on db/seeds.rb
> +@user1 = User.create(user_name: "sasaki", email: "a@g.com", password: "aaaaaa", admin: "true")
存在しないことが保証されているドメインである`example.com`を使うようにしてください。
```suggestion
@user1 = User.create(user_name: "sasaki", email: "a@example.com", password: "aaaaaa", admin: "true")
```

2020-10-10 04:29 UTC, yuji91 commented on db/seeds.rb
> +label10 = Label.create!(name: "sample10")
このようなデータの作成はループ処理で実行した方が良いですね。
時間がかかるようであれば保留しても大丈夫です。

2020-10-10 04:29 UTC, yuji91 commented on spec/spec_helper.rb
> +  # end
こちらも削除をお願いします。

2020-10-10 04:29 UTC, yuji91 commented on spec/system/user_spec.rb
> +        # binding.irb
こちらも削除をお願いします。

2020-10-10 04:29 UTC, yuji91 commented on spec/system/label.spec.rb
> +      FactoryBot.create(:third_task, name: '三番目のタスク', detail: 'テスト３', deadline: '2020/08/30', status: '完了', priority: '高', user: user_a)
`FactoryBot`という記載は設定ファイルに追記を行うことで省略できるようになります。
コード量が大分減るので、ぜひ調べてみてください。
```suggestion
      user_a = create(:user, user_name: 'ユーザーA', email: 'a@example.com')
      create(:task, name: '最初のタスク', detail: 'テスト１', deadline: '2020/08/10', status: '未着手', priority: '低', user: user_a)
      create(:second_task, name: '二番目のタスク', detail: 'テスト２', deadline: '2020/08/20', status: '着手中', priority: '中', user: user_a)
      create(:third_task, name: '三番目のタスク', detail: 'テスト３', deadline: '2020/08/30', status: '完了', priority: '高', user: user_a)
```

2020-10-10 04:29 UTC, yuji91 commented on db/seeds.rb
> +    User.create!(user_name: "test_user#{i + 1}", email: "test#{i + 1}@g.com", password: "ddddd#{i + 1}", admin: "false")
テストデータのユーザーのパスワードについては、すべて固定値で統一しても良いかと思います。

2020-10-10 04:29 UTC, yuji91 commented on config/routes.rb
> +  resources :labels
`resources :tasks`の直下に記載した方が見通しが良くなると思います。

2020-10-10 04:29 UTC, yuji91 commented on app/controllers/labels_controller.rb
> +  end
中身のないメソッドは1行で記載できます。このように書くことで、中身を書き忘れていないことを明示できます。
```suggestion
  def show; end
```

2020-10-10 04:29 UTC, yuji91 commented on app/assets/stylesheets/scaffolds.scss
> +// }
こちらコメントアウトされていますが、不要なファイルであれば削除をお願いします。

2020-10-10 04:29 UTC, yuji91 commented on app/controllers/labels_controller.rb
> +  # GET /labels.json
必要のないコメントは削除をお願いします。

2020-10-10 04:29 UTC, yuji91 commented on app/controllers/labels_controller.rb
> +        format.json { render json: @label.errors, status: :unprocessable_entity }
HTMLで結果を表示できていて`format.json`で出力する必要がなければ、見通しが悪いのでJSON用の処理を記載しない方が良いと思います。

Gemfileのjbuilderの定義をコメントアウトまたは削除してbundle installを実行することで、こちらの定義を作成しない形で rails generateが実行できるようになります。

2020-10-10 06:52 UTC, yuji91 requested changes

2020-10-10 06:52 UTC, yuji91 commented on spec/spec_helper.rb
>    end
以下のDatabaseCleanerの定義については、SystemSpecでは不要となる認識です。
こちらの定義を消して、テスト終了時に作成したデータが削除されることを確認してみてください。
```
  config.before(:suite) do
    DatabaseCleaner.strategy = :transaction
    DatabaseCleaner.clean_with(:truncation)
  end
  config.before(:each) do
    DatabaseCleaner.start
  end
  config.after(:each) do
    DatabaseCleaner.clean
  end
```

2020-10-10 15:12 UTC, hrnrssk commented on app/controllers/tasks_controller.rb
> +  # end
不要なコメントアウトは削除しました。

2020-10-10 15:18 UTC, hrnrssk commented on app/views/tasks/_form.html.erb
> +=end%>
不要なコメントアウトは削除しました。

2020-10-10 15:19 UTC, hrnrssk commented on app/views/tasks/index.html.erb
> +=end%>
不要なコメントアウトは削除しました。

2020-10-10 15:54 UTC, hrnrssk commented on db/migrate/20201004174903_create_labels.rb
> +      t.string :name
labelsテーブルのnameとUsersテーブルのuser_nameとemailとpassword_digestとadminにもnull制約を付与しました。

2020-10-10 16:04 UTC, hrnrssk commented on db/seeds.rb
> +@user1 = User.create(user_name: "sasaki", email: "a@g.com", password: "aaaaaa", admin: "true")
seeds.rbのアドレスのドメインをexample.comに修正しました。

2020-10-10 16:07 UTC, hrnrssk commented on config/routes.rb
> +  resources :labels
resources :labelsをresources :tasksの直下に記載しました。

2020-10-10 16:13 UTC, hrnrssk commented on app/controllers/labels_controller.rb
> +  end
全てのコントローラーの中身のないメソッドは1行で記載しました。

2020-10-10 16:23 UTC, hrnrssk commented on app/assets/stylesheets/scaffolds.scss
> +// }
コメントアウトをやめて有効にしました。

2020-10-10 17:08 UTC, hrnrssk commented on db/migrate/20201004174903_create_labels.rb
> +      t.string :name
うっかりadminにもnull制約を付けてしまったので外しました。

2020-10-10 17:10 UTC, hrnrssk commented on app/controllers/labels_controller.rb
> +        format.json { render json: @label.errors, status: :unprocessable_entity }
JSON用の記述を削除しました。
Gemfileのjbuilderの定義をコメントアウトまたは削除する方法を次から試したいと思います。

2020-10-10 18:18 UTC, hrnrssk commented on spec/spec_helper.rb
>    end
```
  config.before(:each) do
    DatabaseCleaner.start
  end

  config.after(:each) do
    DatabaseCleaner.clean
  end
```
上記は消しても問題ありませんでした。

```
  config.before(:suite) do
    DatabaseCleaner.strategy = :transaction
    DatabaseCleaner.clean_with(:truncation)
  end
```
上記を消すとsystem/label.spec.rbでチェックボックスを見つけられないエラーが出てしまいました。
sample1のチェックボックスを押せるようにcheck 'sample1'への変更やfrom:  'ラベル'を追記してみましたが出来ませんでした。
原因がわからないので消さずにそのままにしてあります。
```
     Failure/Error: check 'task_label_ids_1'
     
     Capybara::ElementNotFound:
       Unable to find checkbox "task_label_ids_1" that is not disabled
     
     [Screenshot]: tmp/screenshots/failures_r_spec_example_groups_nested_nested_a_複数のラベルが付いたタスクを作成できる_645.png

     # ./spec/system/label.spec.rb:33:in `block (4 levels) in <top (required)>'
```

2020-10-11 01:59 UTC, yuji91 commented
99eb432 とコミットIDを半角スペース区切りで記載するとリンクになるので、各指摘事項の返答はこちらのリンクもつけて頂いてもよろしいでしょうか。
このように記載することで、レビュアーが修正内容を確認しやすくなります。

2020-10-11 03:49 UTC, hrnrssk commented on app/controllers/labels_controller.rb
> +  # GET /labels.json
99eb432 不要なコメントは削除しました。

2020-10-11 04:39 UTC, yuji91 commented
こちら5件の指摘事項について、まだ確認頂いていないと思います。

もし保留するものがあれば、返信頂けるとありがたいです。
![image](https://user-images.githubusercontent.com/28836274/95670513-24479300-0bc7-11eb-955c-d0eaca8eaa34.png)

2020-10-11 05:32 UTC, hrnrssk commented on db/seeds.rb
> +label10 = Label.create!(name: "sample10")
変数を通し番号にするやり方を調べますので保留にさせていただきたいと思います。

2020-10-11 05:36 UTC, hrnrssk commented on spec/spec_helper.rb
> +  # end
38cf307 削除しました。

2020-10-11 05:45 UTC, hrnrssk commented on spec/system/user_spec.rb
> +        # binding.irb
3c7be4d 不要なコメントアウトを削除しました。

2020-10-11 05:46 UTC, hrnrssk commented on db/seeds.rb
> +    User.create!(user_name: "test_user#{i + 1}", email: "test#{i + 1}@g.com", password: "ddddd#{i + 1}", admin: "false")
3c7be4d テストデータのユーザーのパスワードを固定値に統一しました。

2020-10-11 05:51 UTC, hrnrssk commented on spec/system/label.spec.rb
> +      FactoryBot.create(:third_task, name: '三番目のタスク', detail: 'テスト３', deadline: '2020/08/30', status: '完了', priority: '高', user: user_a)
調べますので保留にさせていただきたく思います。

2020-10-11 06:45 UTC, yuji91 requested changes

2020-10-11 06:45 UTC, yuji91 commented on spec/spec_helper.rb
>    end
このファイルは https://github.com/rspec/rspec-rails 記載の手順で`rails generate rspec:install`を実行した場合に自動生成されるものなので、生成された際に記載されている設定項目は消さないようにしてください。

この対応を行なった後に、テストが失敗する問題が再発するか確認をお願いします。

2020-10-11 17:22 UTC, hrnrssk commented on spec/spec_helper.rb
>    end
2066958
rspecを再インストールして私が消してしまったspec_helper.rbの内容を復活させましたが
rspecのテストでは同じエラー（task_label_ids_1が見つからない）が出てしまいました。
```
bundle exec rails generate rspec:install
```

rspecの実行のたびにtask_label_ids_1がtask_label_ids_16などに更新されてしまうのがエラーの原因だとわかりました。
おそらくデータベース がテスト後にリセット出来ておらずidの値が増えてしまうのだと思います。
仕方がないのでこちらを再び記述したらテストが通るようになりました。
```
  config.before(:suite) do
    DatabaseCleaner.strategy = :transaction
    DatabaseCleaner.clean_with(:truncation)
  end
```

2020-10-12 16:15 UTC, merged